tasks:
  - before: cp samples/docker-compose.override.yml .
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
    env:
      DB_DATABASE: quanda
      #DB_HOST=localhost
      DB_PORT: 5556
      DB_USER: quanda
      DB_PASS: quanda

ports:
  - port: 8000
    onOpen: open-preview
    visibility: public
  - port: 5556
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mathiasfrohlich.kotlin
    - fwcd.kotlin
