version: "3.9"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS

  app:
    image: alpine
    restart: unless-stopped
    working_dir: /app
    command: ./gradlew bootRun
    environment:
      - PORT:
    depends_on:
      - db
    volumes:
      - ./:/app
    profiles:
      - frontend
