erver:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: quanda
    password: quanda
    url: jdbc:postgresql://localhost:5556/quanda
  jpa:
    hibernate:
      ddl-auto: create-drop
